export const RESET_APP = 'RESET_APP';
// modal actions
export const SHOW_COMPONENT = 'SHOW_COMPONENT';
export const HIDE_COMPONENT = 'HIDE_COMPONENT';
// sign in
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_ERROR = 'CREATE_ACCOUNT_ERROR';
// sign in
export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
// sign out
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_OUT_ERROR = 'SIGN_OUT_ERROR';
// refresh auth
export const REFRESH_AUTH = 'REFRESH_AUTH';
export const REFRESH_AUTH_SUCCESS = 'REFRESH_AUTH_SUCCESS';
export const REFRESH_AUTH_ERROR = 'REFRESH_AUTH_ERROR';
// create node
export const CREATE_NODE = 'CREATE_NODE';
export const CREATE_NODE_SUCCESS = 'CREATE_NODE_SUCCESS';
export const CREATE_NODE_ERROR = 'CREATE_NODE_ERROR';
// fetch nodes
export const FETCH_NODES = 'FETCH_NODES';
export const FETCH_NODES_SUCCESS = 'FETCH_NODES_SUCCESS';
export const FETCH_NODES_ERROR = 'FETCH_NODES_ERROR';
// search nodes
export const SEARCH_NODES = 'SEARCH_NODES';
export const SEARCH_NODES_SUCCESS = 'SEARCH_NODES_SUCCESS';
export const SEARCH_NODES_ERROR = 'SEARCH_NODES_ERROR';
// update node
export const UPDATE_NODE = 'UPDATE_NODE';
export const UPDATE_NODE_SUCCESS = 'UPDATE_NODE_SUCCESS';
export const UPDATE_NODE_ERROR = 'UPDATE_NODE_ERROR';
// update active node
export const UPDATE_ACTIVE_NODE = 'UPDATE_ACTIVE_NODE';
export const UPDATE_ACTIVE_NODE_ERROR = 'UPDATE_ACTIVE_NODE_ERROR';
export const UPDATE_ACTIVE_NODE_SUCCESS = 'UPDATE_ACTIVE_NODE_SUCCESS';
// mark node view
export const MARK_NODE_VIEW = 'MARK_NODE_VIEW';
export const MARK_NODE_VIEW_SUCCESS = 'MARK_NODE_VIEW_SUCCESS';
export const MARK_NODE_VIEW_ERROR = 'MARK_NODE_VIEW_ERROR';
// edit text node
export const EDIT_TEXT_NODE = 'EDIT_TEXT_NODE';
export const EDIT_TEXT_NODE_SUCCESS = 'EDIT_TEXT_NODE_SUCCESS';
export const EDIT_TEXT_NODE_ERROR = 'EDIT_TEXT_NODE_ERROR';
// process text node
export const PROCESS_TEXT_NODE = 'PROCESS_TEXT_NODE';
export const PROCESS_TEXT_NODE_SUCCESS = 'PROCESS_TEXT_NODE_SUCCESS';
export const PROCESS_TEXT_NODE_ERROR = 'PROCESS_TEXT_NODE_ERROR';
// create file node
export const CREATE_FILE_NODE = 'CREATE_FILE_NODE';
export const CREATE_FILE_NODE_SUCCESS = ' CREATE_FILE_NODE_SUCCESS';
export const CREATE_FILE_NODE_ERROR = 'CREATE_FILE_NODE_ERROR';
// link file nodes
export const LINK_FILE_NODES = 'LINK_FILE_NODES';
export const LINK_FILE_NODES_SUCCESS = 'LINK_FILE_NODES_SUCCESS';
export const LINK_FILE_NODES_ERROR = 'LINK_FILE_NODES_ERROR';
// fetch user node
export const FETCH_USER_NODE = 'FETCH_USER_NODE';
export const FETCH_USER_NODE_SUCCESS = 'FETCH_USER_NODE_SUCCESS';
export const FETCH_USER_NODE_ERROR = 'FETCH_USER_NODE_ERROR';
// update user node
export const UPDATE_USER_NODE = 'UPDATE_USER_NODE';
export const UPDATE_USER_NODE_SUCCESS = 'UPDATE_USER_NODE_SUCCESS';
export const UPDATE_USER_NODE_ERROR = 'UPDATE_USER_NODE_ERROR';
// update user avatar
export const UPDATE_USER_AVATAR = 'UPDATE_USER_AVATAR';
export const UPDATE_USER_AVATAR_SUCCESS = 'UPDATE_USER_AVATAR_SUCCESS';
export const UPDATE_USER_AVATAR_ERROR = 'UPDATE_USER_NODE_ERROR';
// update user header image
export const UPDATE_USER_HEADER = 'UPDATE_USER_HEADER';
export const UPDATE_USER_HEADER_SUCCESS = 'UPDATE_USER_HEADER_SUCCESS';
export const UPDATE_USER_HEADER_ERROR = 'UPDATE_USER_HEADER_ERROR';
// create associations
export const CREATE_ASSOCIATION = 'CREATE_ASSOCIATION';
export const CREATE_ASSOCIATION_SUCCESS = 'CREATE_ASSOCIATION_SUCCESS';
export const CREATE_ASSOCIATION_ERROR = 'CREATE_ASSOCIATION_ERROR';
// fetch associations
export const FETCH_ASSOCIATIONS = 'FETCH_ASSOCIATIONS';
export const FETCH_ASSOCIATIONS_SUCCESS = 'FETCH_ASSOCIATIONS_SUCCESS';
export const FETCH_ASSOCIATIONS_ERROR = 'FETCH_ASSOCIATIONS_ERROR';
// reset association list
export const RESET_ASSOCIATIONS = 'RESET_ASSOCIATIONS';
// fetch association link list
export const FETCH_ASSOCIATION_LINK_LIST = 'FETCH_ASSOCIATIONS_LINK_LIST';
export const FETCH_ASSOCIATION_LINK_LIST_SUCCESS = 'FETCH_ASSOCIATIONS_LINK_LIST_SUCCESS';
export const FETCH_ASSOCIATION_LINK_LIST_ERROR = 'FETCH_ASSOCIATIONS_LINK_LIST_ERROR';
// reset association link list
export const RESET_ASSOCIATION_LINK_LIST = 'RESET_ASSOCIATION_LINK_LIST';
// set active node
export const SET_ACTIVE_NODE = 'SET_ACTIVE_NODE';
export const SET_ACTIVE_NODE_SUCCESS = 'SET_ACTIVE_NODE_SUCCESS';
export const SET_ACTIVE_NODE_ERROR = 'SET_ACTIVE_NODE_ERROR';
// clear active node
export const CLEAR_ACTIVE_NODE = 'CLEAR_ACTIVE_NODE';
// delete node
export const DELETE_NODE = 'DELETE_NODE';
export const DELETE_NODE_SUCCESS = 'DELETE_NODE_SUCCESS';
export const DELETE_NODE_ERROR = 'DELETE_NODE_ERROR';
// remove from association list
export const REMOVE_FROM_ASSOCIATION_LIST = 'REMOVE_FROM_ASSOCIATION_LIST';
// delete association link
export const DELETE_ASSOCIATION_LINK = 'DELETE_ASSOCIATION_LINK';
export const DELETE_ASSOCIATION_LINK_SUCCESS = 'DELETE_ASSOCIATION_LINK_SUCCESS';
export const DELETE_ASSOCIATION_LINK_ERROR = 'DELETE_ASSOCIATION_LINK_ERROR';
// generate instance export
export const GENERATE_EXPORT = 'GENERATE_EXPORT';
export const GENERATE_EXPORT_ERROR = 'GENERATE_EXPORT_ERROR';
export const GENERATE_EXPORT_SUCCESS = 'GENERATE_EXPORT_SUCCESS';
// fetch graph nodes
export const FETCH_GRAPH_DATA = 'FETCH_GRAPH_DATA';
export const FETCH_GRAPH_DATA_ERROR = 'FETCH_GRAPH_DATA_ERROR';
export const FETCH_GRAPH_DATA_SUCCESS = 'FETCH_GRAPH_DATA_SUCCESS';
